# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: e1b1ff58fbeafaf3d3c6c78d5d316d925bbac9462cb27fc06056f843f44c8a858084668604961c779f5228978e350a7e6ebaf1b4e8a107a0a3ccd098a9521d2d

test:
  secret_key_base: e27900361e2bd130a7f358421f812ee66465dcadfac92921dd09a94a56816894b10a09e23e1fc066e79c36474a4d1199a5b12f721c892fbc1e03bac84ef50b41

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
